routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
	return view('welcome');
});

Route::get('/error-500', function () {
	return view('error-500');
})->name('error500');

Route::get('/error-404', function () {
	return view('error-404');
})->name('error404');

Route::get('clean', function () {
	\Artisan::call('config:cache');
	\Artisan::call('route:clear');
	\Artisan::call('optimize:clear');
	return "Done!";
});

Route::get('/client-register', 'UserController@createClientRegisterPage')->name('ClientRegister');
Route::post('client/request', 'UserController@saveClientRegister')->name('client.request.register');
Route::post('/existusername', 'UserController@existusername');
Route::post('/existcontactno', 'UserController@existcontactno');
Route::get('userlogout', 'Auth\LoginController@loggedOut')->name('user.logout');

Route::get('get-state-list1', 'UserController@getStateList');
Route::get('get-city-list1', 'UserController@getCityList');

Auth::routes();

Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function () {

	Route::get('/userpanel', 'UserController@userpanelindex')->name('userpanel');
	Route::get('/addressbook', 'UserController@addressindex')->name('addressindex');
	Route::get('/multisms', 'UserController@multismsindex')->name('multismsindex');
	Route::get('/groupsms', 'UserController@groupsmsindex')->name('groupsmsindex');
	Route::get('/singlesms', 'UserController@singlesmsindex')->name('multismsindex');
	Route::get('/bulksms', 'UserController@bulksmsindex')->name('bulksmsindex');
	Route::get('/apikey', 'UserController@apikeyindex')->name('apikeyindex');
	Route::get('/transaction-history', 'MembersController@transaction_history')->name('transaction-history');

	Route::get('/wallet', 'MembersController@storepremiumRegister')->name('wallet.submit');
	Route::get('/Rechargewallet', 'MembersController@index')->name('addmoney');

	Route::post('/payment-success', 'MembersController@payment_success');

	Route::get('/premiumRegister/{token?}', 'PremiumsignupController@index');
	Route::post('/premiumRegister/create', 'PremiumsignupController@store')->name('create.premiumRegister');
	Route::post('/premiumRegister/create_premiumRegister', 'PremiumsignupController@storepremiumRegister');

	Route::post('create/usergroup/', 'ContactController@createusergroup')->name('contact.usergroup.create');

	/**
	 * Roles, Permission and Users Permission Modules
	 */
	Route::resource('roles', 'RoleController');
	Route::resource('users', 'UserController');
	Route::resource('products', 'ProductController');
	Route::get('myprofile/view', 'UserController@amyprofileView')->name('amyprofile.view');
	Route::get('editprofile', 'UserController@aeditProfileForm')->name('aprofile.update');
	Route::post('editprofile/request/{id}', 'UserController@aupdateProfile')->name('aprofile.update.request');

	Route::get('user/change-password', 'ChangePasswordController@index')->name('changepassword');
	Route::post('user/change-password', 'ChangePasswordController@store')->name('change.password');

	Route::get('userpanel/change-password', 'ChangePasswordController@userindex')->name('user.changepassword1');
	Route::post('userpanel/change-password/request', 'ChangePasswordController@userstore')->name('user.change.password');

	Route::get('edituserprofile', 'UserController@usereditProfileForm')->name('userprofile.update');
	Route::post('edituserprofile/request/{id}', 'UserController@userupdatedetails')->name('userupdatedetails.update.request');

	/**
	 * SMS Contacts
	 */
	Route::prefix('contacts')->group(function () {

		Route::get('show', 'ContactController@showContact')->name('contact.show');
		Route::get('create/new/{uuid?}', 'ContactController@createContact')->name('contact.create');
		Route::post('create-request/{uuid?}', 'ContactController@storeData')->name('contact.create.request');
		Route::get('remove/{uuid?}', 'ContactController@deleteContact')->name('contact.remove');

		/**
		 * Group Contact
		 */
		Route::get('group/show', 'ContactController@showGroupContact')->name('contact.group.show');
		Route::get('create/group/{uuid?}', 'ContactController@createGroupContact')->name('contact.group.create');
		Route::get('remove/group/{uuid?}', 'ContactController@deleteGroupContact')->name('contact.group.remove');

		Route::post('create-group-request/{uuid?}', 'ContactController@groupStoreData')->name('contact.group.create.request');

	});

	Route::prefix('user/contacts')->group(function () {

		Route::post('usercontactcreate-request/{uuid?}', 'ContactController@usercontactstoreData')->name('user.contacts.create.request');
		Route::post('usermultiplecontacts-request/{uuid?}', 'ContactController@usermultiplecontactstoreData')->name('user.multiplecontacts.create.request');
		Route::get('/usercontactcreate-request/edit/{id}', 'ContactController@usercontact_edit')->name('user.contacts.edit');
		Route::post('/usercontact/request/update/{id}', 'ContactController@usercontact_update')->name('user.contacts.update');

		Route::post('/usercontact/delete/{id}', 'ContactController@usercontact_delete')->name('user.contacts.delete');
		Route::get('/usergroup/delete/{id}', 'ContactController@usergroup_delete')->name('user.groups.delete');

	});

	Route::get('usercontact/search', 'ContactController@searchcontact')->name('searchcontact');
	Route::get('smsgroupid/select', 'ContactController@smsgroupid')->name('smsgroupid.select');
	Route::get('usercontactgroup/search', 'ContactController@searchcontactgroup')->name('searchcontactgroup');
	Route::get('usercontact/editgroupcontact', 'ContactController@EditGroupContact')->name('editgroupcontact');

	Route::get('phonebook', 'PhoneBookController@index')->name('phonebook');
	Route::get('create-phonebook', 'PhoneBookController@create')->name('phonebook.create');
	Route::post('/store-phonebook', 'PhoneBookController@store')->name('phonebook.store');
	Route::get('/phonebook/edit/{id}', 'PhoneBookController@edit')->name('phonebook.edit');
	Route::get('/phonebook/delete/{id}', 'PhoneBookController@delete1')->name('phonebook.delete');
	Route::post('/phonebook/request/update/{id}', 'PhoneBookController@update')->name('phonebook.update');

	Route::get('allphonebook', 'PhoneBookController@allPhoneBook')->name('allphonebook');
	Route::get('change/phonebook-status/{id}', 'PhoneBookController@changephonebookStatus_datatable')->name('change.phonebook_datatable.status');

	Route::get('sms_package', 'SmsPackageController@index')->name('sms_package');
	Route::get('create-sms_package', 'SmsPackageController@create')->name('sms_package.create');
	Route::post('/store-sms_package', 'SmsPackageController@store')->name('sms_package.store');
	Route::get('/sms_package/edit/{id}', 'SmsPackageController@edit')->name('sms_package.edit');
	Route::get('/sms_package/delete/{id}', 'SmsPackageController@delete1')->name('sms_package.delete');
	Route::post('/sms_package/request/update/{id}', 'SmsPackageController@update')->name('sms_package.update');

	Route::get('allsmspackage', 'SmsPackageController@allSmsPackage')->name('allsmspackage');
	Route::get('change/smspackage-status/{id}', 'SmsPackageController@changeSmsPackageStatus_datatable')->name('change.sms_package_datatable.status');

	Route::get('user_sms_package', 'UserSmsPackageController@index')->name('user_sms_package');
	Route::get('create-user_sms_package', 'UserSmsPackageController@create')->name('user_sms_package.create');
	Route::post('/store-user_sms_package', 'UserSmsPackageController@store')->name('user_sms_package.store');
	Route::get('/user_sms_package/edit/{id}', 'UserSmsPackageController@edit')->name('user_sms_package.edit');
	Route::get('/user_sms_package/delete/{id}', 'UserSmsPackageController@delete1')->name('user_sms_package.delete');
	Route::post('/user_sms_package/request/update/{id}', 'UserSmsPackageController@update')->name('sms_package.update');

	Route::get('allusersmspackage', 'UserSmsPackageController@alluserSmsPackage')->name('allusersmspackage');
	Route::get('change/usersmspackage-status/{id}', 'UserSmsPackageController@changeUserSmsPackageStatus_datatable')->name('change.user_sms_package_datatable.status');
	Route::get('get-smspackage-list', 'UserSmsPackageController@getSmsPackageList');

	/**
	 * External API
	 */
	Route::prefix('third-party-api')->namespace('ExternalAPI')->group(function () {
		Route::get('all/apis', 'ThirdPartyAPIController@showAllAPIS')->name('list.external.apis');
		Route::get('add/new/apis', 'ThirdPartyAPIController@addNewAPIS')->name('add.new.apis');
		Route::post('externalapi/create/apis/request', 'ThirdPartyAPIController@importNewAPIS')->name('externalapi.create.request');
		Route::get('externalapi/remove/{uuid}', 'ThirdPartyAPIController@removeAPIS')->name('externalapi.remove');
		Route::get('externalapi/status/{uuid}', 'ThirdPartyAPIController@changeExternalAPIStatus')->name('externalapi.chnage.status');

		// SEND SMS
		Route::get('sendsms/single/sms', 'SendSMSController@sendSingleSMSForm')->name('sendsms.single.view');
		Route::post('sendsms/single/sms/request', 'SendSMSController@sendSingleSMSRequest')->name('send.singlesms.request');
		Route::post('user/sendsms/single/sms/request', 'SendSMSController@sendUserSingleSMSRequest')->name('send.usersinglesms.request');

		Route::get('sendsms/multi/sms', 'SendSMSController@sendMultiSMS')->name('sendsms.multi.view');
		Route::post('sendsms/multi/sms/request', 'SendSMSController@SendMultiSMSRequest')->name('send.multisms.request');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;
use Illuminate\Database\Eloquent\SoftDeletes;


class User extends Authenticatable
{
    use Notifiable, HasRoles, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

resources/views/users/changePassword.blade.php
@extends('layouts.app')

@section('extracss')

@endsection

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark">Change Password</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="{{ route('users.index') }}">Users</a></li>
                <li class="breadcrumb-item active">Change Password</li>
              </ol>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                
                <div class="card-body">
                    <!-- general form elements -->

                        <div class="card card-primary">
                    <form method="POST" action="{{ route('change.password') }}" enctype="multipart/form-data">
                        @csrf
                        <div class="">
                            
                                    <div class="card-header">Change password</div>
                                    <div class="card-body row">
                                         

                                        <div class="form-group col-md-4">
                                            <label>Old Password</label>
                                            <input type="password" name="current_password" id="password" class="form-control" placeholder="Enter Current Password" required>
                                            {!! $errors->first('current_password', '<p class="help-block" style="color: #d81212;font-weight: 600;">:message</p>') !!}
                                            <div class="valid-feedback">
                                                Looks good!
                                            </div>
                                        </div>
                                        <div class="form-group col-md-4">
                                            <label>New Password</label>
                                            <input type="password" name="new_password" id="new_password" class="form-control" placeholder="Enter New Password" required>
                                            <div class="valid-feedback">
                                                Looks good!
                                            </div>
                                            {!! $errors->first('new_password', '<p class="help-block" style="color: #d81212;font-weight: 600;">:message</p>') !!}
                                        </div>
                                        <div class="form-group col-md-4">
                                            <label>Confirm Password</label>
                                            <input type="password" name="new_confirm_password" id="new_confirm_password" class="form-control" placeholder="Enter Confirmed Password" required>
                                            <div class="valid-feedback">
                                                Looks good!
                                            </div>
                                            {!! $errors->first('new_confirm_password', '<p class="help-block" style="color: #d81212;font-weight: 600;">:message</p>') !!}
                                        </div>
                                        
                                    </div>
                                

                            
                            
                            <div class="col-md-12 text-center">
                            	<div class="card-header">
				                    
				                    <button class="btn btn-primary" type="submit" value="Submit Form" style="float: right;">Update Password</button>
				                </div>
                                

                            </div>



                        </div>
                    </form>
                 </div>
                    <!-- /.card -->
                </div>
                    
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->

@endsection

@section('extrajs')
   
       
    
    
@endsection

resources/views/users/create.blade.php
@extends('layouts.app')

@section('extracss')

@endsection

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark">Users</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="{{ route('users.index') }}">Users</a></li>
                <li class="breadcrumb-item active">Create User</li>
              </ol>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                <!-- /.card-header -->
                    <div class="card-body">
                        <!-- general form elements -->
                        <div class="card card-primary">

                            {!! Form::open(array('route' => 'users.store','method'=>'POST')) !!}
                                <div class="row">
                                    <div class="col-xs-12 col-sm-12 col-md-12">
                                        <div class="form-group">
                                            <strong>Name:</strong>
                                            {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!}
                                        </div>
                                    </div>
                                    <div class="col-xs-12 col-sm-12 col-md-12">
                                        <div class="form-group">
                                            <strong>Email:</strong>
                                            {!! Form::text('email', null, array('placeholder' => 'Email','class' => 'form-control')) !!}
                                        </div>
                                    </div>
                                    <div class="col-xs-12 col-sm-12 col-md-12">
                                        <div class="form-group">
                                            <strong>Password:</strong>
                                            {!! Form::password('password', array('placeholder' => 'Password','class' => 'form-control')) !!}
                                        </div>
                                    </div>
                                    <div class="col-xs-12 col-sm-12 col-md-12">
                                        <div class="form-group">
                                            <strong>Confirm Password:</strong>
                                            {!! Form::password('confirm-password', array('placeholder' => 'Confirm Password','class' => 'form-control')) !!}
                                        </div>
                                    </div>
                                    <div class="col-xs-12 col-sm-12 col-md-12">
                                        <div class="form-group">
                                            <strong>Role:</strong>
                                            {!! Form::select('roles[]', $roles,[], array('class' => 'form-control','multiple')) !!}
                                        </div>
                                    </div>
                                    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </div>
                                </div>
                            {!! Form::close() !!}

                        </div>
                    <!-- /.card -->
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->

@endsection

@section('extrajs')
    <script>
        $(function () {

        });
    </script>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('extracss')

@endsection

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark">Users</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="{{ route('users.index') }}">Users</a></li>
                <li class="breadcrumb-item active">Create User</li>
              </ol>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                <!-- /.card-header -->
                    <div class="card-body">
                        <!-- general form elements -->
                        <div class="card card-primary">

                            {!! Form::model($user, ['method' => 'PATCH','route' => ['users.update', $user->id]]) !!}
                                <div class="row">
                                    <div class="col-xs-12 col-sm-12 col-md-12">
                                        <div class="form-group">
                                            <strong>Name:</strong>
                                            {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!}
                                        </div>
                                    </div>
                                    <div class="col-xs-12 col-sm-12 col-md-12">
                                        <div class="form-group">
                                            <strong>Email:</strong>
                                            {!! Form::text('email', null, array('placeholder' => 'Email','class' => 'form-control')) !!}
                                        </div>
                                    </div>
                                    <div class="col-xs-12 col-sm-12 col-md-12">
                                        <div class="form-group">
                                            <strong>Password:</strong>
                                            {!! Form::password('password', array('placeholder' => 'Password','class' => 'form-control')) !!}
                                        </div>
                                    </div>
                                    <div class="col-xs-12 col-sm-12 col-md-12">
                                        <div class="form-group">
                                            <strong>Confirm Password:</strong>
                                            {!! Form::password('confirm-password', array('placeholder' => 'Confirm Password','class' => 'form-control')) !!}
                                        </div>
                                    </div>
                                    <div class="col-xs-12 col-sm-12 col-md-12">
                                        <div class="form-group">
                                            <strong>Role:</strong>
                                            {!! Form::select('roles[]', $roles,$userRole, array('class' => 'form-control','multiple')) !!}
                                        </div>
                                    </div>
                                    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                        <button type="submit" class="btn btn-primary">Update</button>
                                    </div>
                                </div>
                            {!! Form::close() !!}

                        </div>
                    <!-- /.card -->
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->

@endsection

@section('extrajs')
    <script>
        $(function () {

        });
    </script>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('extracss')
<link rel="stylesheet" href="{{ asset('lte/plugins/datatables-bs4/css/dataTables.bootstrap4.css') }}">
@endsection

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
            <h1 class="m-0 text-dark">Clients</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="Javascript::void(0)">Users</a></li>
                <li class="breadcrumb-item active">All Clients</li>
            </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="row">
          <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">All Clients</h3>
                    <a href="{{ route('users.create') }}" class="btn btn-info" style="float: right">Add User+</a>
                </div>

              <!-- /.card-header -->
                <div class="card-body">
                    <table id="clientData-Table" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Role</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($data as $key => $user)
                                <tr>
                                    <td>{{ $user->name }}</td>
                                    <td>{{ $user->email }}</td>
                                    <td>
                                        @if(!empty($user->getRoleNames()))
                                          @foreach($user->getRoleNames() as $v)
                                             <label class="badge badge-success">{{ $v }}</label>
                                          @endforeach
                                        @endif
                                    </td>
                                    <td>
                                        <a class="btn btn-info" href="{{ route('users.show',$user->id) }}">Show</a>
                                        <a class="btn btn-primary" href="{{ route('users.edit',$user->id) }}">Edit</a>
                                         {!! Form::open(['method' => 'DELETE','route' => ['users.destroy', $user->id],'style'=>'display:inline']) !!}
                                             {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                                         {!! Form::close() !!}
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
@endsection


@section('extrajs')
<!-- DataTables -->
<script src="{{ asset('lte/plugins/datatables/jquery.dataTables.js') }}"></script>
<script src="{{ asset('lte/plugins/datatables-bs4/js/dataTables.bootstrap4.js') }}"></script>

<script>

</script>
@endsection

resources/views/users/show.blade.php
@extends('layouts.app')

@section('extracss')

@endsection

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark">Show User</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="{{ route('users.index') }}">Users</a></li>
                <li class="breadcrumb-item active">View User</li>
              </ol>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                    <!-- /.card-header -->
                        <div class="card-body">
                            <!-- general form elements -->
                            <div class="card card-primary">

                                <div class="row">
                                    <div class="col-xs-12 col-sm-12 col-md-12">
                                        <div class="form-group">
                                            <strong>Name:</strong>
                                            {{ $user->name }}
                                        </div>
                                    </div>
                                    <div class="col-xs-12 col-sm-12 col-md-12">
                                        <div class="form-group">
                                            <strong>Email:</strong>
                                            {{ $user->email }}
                                        </div>
                                    </div>
                                    <div class="col-xs-12 col-sm-12 col-md-12">
                                        <div class="form-group">
                                            <strong>Roles:</strong>
                                            @if(!empty($user->getRoleNames()))
                                                @foreach($user->getRoleNames() as $v)
                                                    <label class="badge badge-success">{{ $v }}</label>
                                                @endforeach
                                            @endif
                                        </div>
                                    </div>
                                </div>

                            </div>
                            <!-- /.card -->
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->

@endsection